invenio: better secret key and salts management
inveniosoftware/helm-invenio pull request #148
Opened 2024-12-16 13:17 UTC by egabancho

* Adds missing salts to harden security.

* Deprecates plain keys and forces to use secrets for them.

* Automatically generates secret key and salts if no secret is provided.

2024-12-17 21:02 UTC, lindhe requested changes

2024-12-17 22:06 UTC, egabancho commented on charts/invenio/templates/_helpers.tpl
> +  {{- print (tpl .Values.invenio.sentry.existingSecret .) -}}
That's a rebase error 😉

2024-12-21 14:26 UTC, lindhe commented on charts/invenio/templates/NOTES.txt
> +{{- if .Values.invenio.existing_secret}}
```suggestion
{{- if .Values.invenio.existing_secret }}
```

2024-12-21 14:27 UTC, lindhe commented on charts/invenio/templates/_helpers.tpl
> +  {{- print (tpl .Values.invenio.existingSecret .) -}}
Isn't the `print` statement redundant?

2024-12-21 14:28 UTC, lindhe commented
I've posted some final comments. After they are fixed I'll approve this.

2025-01-08 13:44 UTC, egabancho commented on charts/invenio/templates/_helpers.tpl
> +  {{- print (tpl .Values.invenio.existingSecret .) -}}
That's what I thought. Then I started seeing things like that on bitnami's helm charts, `{{- print "networking.k8s.io/v1" -}}` or even `{{- printf "%s" (tpl $secretName $) -}}`, and I figured that there might be a security/escape characters situation here that I am not aware of ... but I couldn't find anything on the documentation that references such a thing.
Do you happen to know anything about that?

2025-01-09 13:10 UTC, lindhe commented on charts/invenio/templates/_helpers.tpl
> +  {{- print (tpl .Values.invenio.existingSecret .) -}}
Not that I'm aware of. 🤔

2025-01-10 08:56 UTC, egabancho commented on charts/invenio/templates/_helpers.tpl
> +  {{- print (tpl .Values.invenio.existingSecret .) -}}
I asked ChatGTP about it 😅
It says the `print` is unnecessary and there are no security implications ... I'm not to expend more time on it, I just removed it.

2025-01-10 09:04 UTC, lindhe approved these changes

2025-01-10 09:27 UTC, merged